// Generated by dts-bundle-generator v9.5.1

import React$1 from "react";
import { Root } from "react-dom/client";

export interface RenderContainer extends HTMLDivElement {
  root: Root;
  render: (component: React$1.ReactNode) => void;
  component: React$1.ReactElement;
}
export type EventHandler = (event: Event) => void;
export interface ReactTest {
  root: RenderContainer | null;
  nodes: Node[];
  events: Record<string, EventHandler[]>;
  error?: Error;
  length: number;
  [Symbol.iterator](): Generator<Node, void, unknown>;
  attr(name: string): string | null;
  array(): Node[];
  array(callback: string): unknown[];
  array<T>(callback: (node: Node, index: number, arr: Node[]) => T): T[];
  change(value: string | boolean): Promise<null>;
  children(selector?: string): ReactTest;
  click(): Promise<void>;
  closest(selector?: string): ReactTest;
  data(name: string): string | null;
  delay(time: number): Promise<void>;
  each(callback?: (node: Node, index: number, arr: Node[]) => void): ReactTest;
  eq(index?: number): ReactTest;
  filter(
    selector?: string | ReactTest | ((node: Node, index: number) => boolean),
  ): ReactTest;
  find(selector?: string): ReactTest;
  first(): ReactTest;
  get<T extends Node = Node>(index?: number): T | null;
  html(): string;
  is(selector?: string | ReactTest | ((node: Node) => boolean)): boolean;
  last(): ReactTest;
  map(
    callback?: (node: Node) => Node | NodeList | Node[] | null | undefined,
  ): ReactTest;
  not(filter?: string | ReactTest): ReactTest;
  parent(): ReactTest;
  props(
    props:
      | Record<string, unknown>
      | ((prev: Record<string, unknown>) => Record<string, unknown>),
  ): ReactTest;
  render(component: unknown): ReactTest;
  siblings(selector?: string): ReactTest;
  submit(): Promise<void>;
  text(): string;
  trigger(type: string, extra?: Record<string, unknown>): Promise<void>;
  type(input: string): Promise<void>;
}
declare const $: {
  new (
    obj: unknown,
    ctx?: Partial<Pick<ReactTest, "events" | "root">>,
  ): ReactTest;
  (obj: unknown, ctx?: Partial<Pick<ReactTest, "events" | "root">>): ReactTest;
  prototype: ReactTest;
};
/**
 * Wait until the specified condition is fulfilled. Use this whenever a
 * component updates asynchronously — data fetching, timers, animations, etc.
 *
 * ```js
 * // Wait for a callback to return truthy
 * await until(() => $demo.text() === "Loaded");
 *
 * // Wait for an element to match a CSS selector
 * await until($button).is(".active");
 *
 * // Wait for children to appear
 * await until($list).find("li");
 * ```
 *
 * Works with components that load data asynchronously:
 *
 * ```js
 * const $demo = $(<UserProfile id={1} />);
 * expect($demo).toHaveText("Loading...");
 * await until(() => $demo.text() !== "Loading...");
 * expect($demo).toHaveText("Alice");
 * ```
 *
 * **[→ Full until() Docs](https://react-test.dev/documentation#until)**
 */
export function until(arg?: (() => unknown) | object): any;

export { $ as default };

export {};
interface ReactTestMatchers<R> {
  toBeEnabled(): R;
  toHaveAttribute(attr: string, val?: string | RegExp | boolean): R;
  toHaveClass(...classes: (string | string[])[]): R;
  toHaveError(message?: string | RegExp): R;
  toHaveHtml(html: string): R;
  toHaveStyle(styles: string | Record<string, unknown>): R;
  toHaveText(text: string): R;
  toHaveValue(value?: string | boolean | number): R;
  toMatchSelector(selector: string): R;
}

declare global {
  namespace jest {
    interface Matchers<R> extends ReactTestMatchers<R> {}
  }
}

declare module "vitest" {
  interface Matchers<T = any> extends ReactTestMatchers<T> {}
}
