import server from "live-server";
import build from "./build.js";

const buildHandler = async (req, res, next) => {
  try {
    await build();
    next();
  } catch (error) {
    next(error);
  }
};

server.start({
  wait: 100,
  root: "./docs",
  watch: ["./readme.md", "./docs", "./src"],

  // Put here the autogenerated files to avoid infinite loops:
  ignore: ["./docs/index.html", "./docs/style.min.css", "./docs/index.min.js"],
  middleware: [buildHandler]
});
