import server from "live-server";
import build from "./build.js";

server.start({
  wait: 100,
  root: "./docs",
  watch: ["./readme.md", "./docs", "./src"],

  // Put here the autogenerated files to avoid infinite loops:
  ignore: ["./docs/index.html", "./docs/style.min.css"],
  middleware: [build]
});
