name: tests

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Runs every 1st of the month at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version: [18, 19]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install specific React version
        run: npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}
      - name: install dependencies
        run: npm install
      - name: npm test
        run: npm test
        env:
          CI: true
