name: tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version: [18, 19]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js latest
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Install specific React version
        run: npm install react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}
      - name: Install dependencies
        run: npm install
      - name: Run the linter
        run: npm run lint
      - name: Run the tests
        run: npm test
        env:
          CI: true

  demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js latest
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
      - name: Use Bun latest
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: npm install
      - name: Run the demo tests
        run: npm run test:demo
